In [1]:
import numpy as np

def linearRegression(data_X,data_Y,learningRate,loopNum):
    W = np.zeros(shape=[1, data_X.shape[1]])
    # W的shape取决于特征个数，而x的行是样本个数，x的列是特征值个数
    # 所需要的W的形式为 行=特征个数，列=1 这样的矩阵。但也可以用1行，再进行转置：W.T
    # X.shape[0]取X的行数，X.shape[1]取X的列数
    b = 0

    #梯度下降
    for i in range(loopNum):
        W_derivative = np.zeros(shape=[1, data_X.shape[1]])
        b_derivative, cost = 0, 0

        WXPlusb = np.dot(data_X, W.T) + b   # W.T：W的转置
        W_derivative += np.dot((WXPlusb - data_Y).T, data_X)  # np.dot:矩阵乘法
        b_derivative += np.dot(np.ones(shape=[1, data_X.shape[0]]), WXPlusb - data_Y)
        cost += (WXPlusb - data_Y)*(WXPlusb - data_Y)
        W_derivative = W_derivative / data_X.shape[0]  # data_X.shape[0]:data_X矩阵的行数，即样本个数
        b_derivative = b_derivative / data_X.shape[0]


        W = W - learningRate*W_derivative
        b = b - learningRate*b_derivative

        cost = cost/(2*data_X.shape[0])
        if i % 100 == 0:
            print(cost)
    print(W)
    print(b)

if __name__== "__main__":
    X = np.random.normal(0, 10, 100)
    noise = np.random.normal(0, 0.05, 20)
    W = np.array([[3, 5, 8, 2, 1]])  #设5个特征值
    X = X.reshape(20, 5)     #reshape成20行5列
    noise = noise.reshape(20, 1)
    Y = np.dot(X, W.T)+6 + noise
    linearRegression(X, Y, 0.003, 5000)

[[2.18510731e+02]
 [2.36061702e+02]
 [1.23969907e+03]
 [1.97643219e+03]
 [3.40573167e+02]
 [2.30182510e+01]
 [6.22825631e-03]
 [1.03638387e+02]
 [3.12742675e+02]
 [9.77548981e+00]
 [7.68713812e+00]
 [4.20930959e+02]
 [1.99134326e+03]
 [3.35733496e+02]
 [1.26618770e+02]
 [5.55742813e+00]
 [5.55911468e+02]
 [5.11118160e+01]
 [1.26255870e+03]
 [2.19589141e+00]]
[[0.40690089]
 [0.34324706]
 [1.02408952]
 [0.16356294]
 [0.44025067]
 [0.64023821]
 [0.70079519]
 [0.72235554]
 [0.43704148]
 [0.89859413]
 [0.23716396]
 [0.57615314]
 [0.04499542]
 [0.2058281 ]
 [0.70071467]
 [0.47817683]
 [0.4577668 ]
 [0.34725788]
 [0.4614366 ]
 [0.60187923]]
[[0.234725  ]
 [0.19602041]
 [0.58330124]
 [0.09231113]
 [0.25024938]
 [0.36649458]
 [0.40262403]
 [0.40917536]
 [0.24994262]
 [0.51494428]
 [0.13627706]
 [0.33016679]
 [0.02574451]
 [0.11745835]
 [0.39991235]
 [0.27381902]
 [0.26098704]
 [0.19798343]
 [0.26714906]
 [0.34277307]]
[[0.13568562]
 [0.11192407]
 [0.33209913]
 [0.0517945 ]
 [0.14199002]
 [0.210